from os import PathLike
from typing import Any, Optional, Sequence, Union

import numpy as np
import numpy.typing as npt

ArrayLike = npt.ArrayLike
SceneLike = Union[str, PathLike, dict]

__version__: str
PANDA_READY: list[float]
UR5_HOME: list[float]

class PlanningError(RuntimeError): ...

def simd_backend() -> str: ...

class Robot:
    @staticmethod
    def panda() -> Robot: ...
    @staticmethod
    def ur5() -> Robot: ...
    @staticmethod
    def from_toml(text: str) -> Robot: ...
    @property
    def name(self) -> str: ...
    @property
    def dof(self) -> int: ...
    @property
    def num_spheres(self) -> int: ...
    @property
    def joint_names(self) -> list[str]: ...
    @property
    def lower_limits(self) -> npt.NDArray[np.float64]: ...
    @property
    def upper_limits(self) -> npt.NDArray[np.float64]: ...
    def within_limits(self, q: ArrayLike) -> bool: ...
    def fk(self, q: ArrayLike) -> npt.NDArray[np.float64]: ...
    def frames(self, q: ArrayLike) -> npt.NDArray[np.float64]: ...
    def spheres(self, q: ArrayLike) -> npt.NDArray[np.float64]: ...
    def ik(
        self,
        target: ArrayLike,
        seed_q: Optional[ArrayLike] = None,
        *,
        seed: int = 0,
        restarts: int = 32,
        position_tolerance: float = 1e-4,
        orientation_tolerance: float = 1e-3,
    ) -> Optional[npt.NDArray[np.float64]]: ...
    def with_attached(self, name: str, spheres: ArrayLike) -> Robot: ...
    def without_attached(self, name: str) -> Robot: ...
    @property
    def attached(self) -> list[str]: ...

class Environment:
    def __init__(self) -> None: ...
    @staticmethod
    def from_scene(scene: SceneLike, skip: Sequence[str] = ...) -> Environment: ...
    def add_sphere(self, center: ArrayLike, radius: float) -> None: ...
    def add_capsule(self, a: ArrayLike, b: ArrayLike, radius: float) -> None: ...
    def add_box(self, center: ArrayLike, size: ArrayLike, yaw: float = 0.0, name: str = "") -> None: ...
    def add_cuboid(
        self, center: ArrayLike, half_extents: ArrayLike, rotation: Optional[ArrayLike] = None
    ) -> None: ...
    def add_pointcloud(self, points: ArrayLike, point_radius: float = 0.0, cell_size: float = 0.05) -> None: ...
    def __len__(self) -> int: ...

class PlanResult:
    @property
    def path(self) -> npt.NDArray[np.float64]: ...
    @property
    def length(self) -> float: ...
    @property
    def initial_length(self) -> float: ...
    @property
    def iterations(self) -> int: ...
    @property
    def tree_sizes(self) -> tuple[int, int]: ...
    @property
    def planning_time(self) -> float: ...
    @property
    def simplify_time(self) -> float: ...
    @property
    def total_time(self) -> float: ...
    @property
    def checker(self) -> str: ...
    def interpolate(self, step: float = 0.05) -> npt.NDArray[np.float64]: ...
    def __len__(self) -> int: ...

class Planner:
    def __init__(
        self,
        robot: Robot,
        environment: Optional[Environment] = None,
        checker: str = "simd",
        resolution: float = 32.0,
    ) -> None: ...
    @property
    def checker(self) -> str: ...
    def config_valid(self, q: ArrayLike) -> bool: ...
    def configs_valid(self, qs: ArrayLike) -> npt.NDArray[np.bool_]: ...
    def motion_valid(self, a: ArrayLike, b: ArrayLike) -> bool: ...
    def plan(
        self,
        start: ArrayLike,
        goal: ArrayLike,
        *,
        seed: int = 0,
        range: float = 1.0,
        max_iterations: int = 100000,
        simplify: bool = True,
    ) -> PlanResult: ...

class PregraspResult:
    @property
    def pose(self) -> npt.NDArray[np.float64]: ...
    @property
    def goal(self) -> npt.NDArray[np.float64]: ...
    @property
    def grasp_width(self) -> float: ...
    @property
    def plan(self) -> PlanResult: ...

def plan_to_pregrasp(
    robot: Robot,
    scene: SceneLike,
    object_id: str,
    start: ArrayLike,
    *,
    clearance: float = 0.1,
    seed: int = 0,
) -> PregraspResult: ...

class PickResult:
    @property
    def pregrasp_pose(self) -> npt.NDArray[np.float64]: ...
    @property
    def grasp_pose(self) -> npt.NDArray[np.float64]: ...
    @property
    def grasp_width(self) -> float: ...
    @property
    def to_pregrasp(self) -> PlanResult: ...
    @property
    def approach(self) -> npt.NDArray[np.float64]: ...
    @property
    def retreat(self) -> npt.NDArray[np.float64]: ...
    @property
    def place(self) -> Optional[PlanResult]: ...
    @property
    def attached_spheres(self) -> npt.NDArray[np.float64]: ...
    @property
    def object_in_tcp(self) -> npt.NDArray[np.float64]: ...

def plan_pick(
    robot: Robot,
    scene: SceneLike,
    object_id: str,
    start: ArrayLike,
    *,
    place: Optional[ArrayLike] = None,
    clearance: float = 0.1,
    grasp_depth: float = 0.02,
    seed: int = 0,
) -> PickResult: ...
