"""Generate crates/motionamigo/robots/panda.toml from VAMP's spherized Panda URDF and SRDF.

Usage:
    python tools/gen_panda_toml.py path/to/vamp/resources/panda > crates/motionamigo/robots/panda.toml

The sphere decomposition comes from resources/panda/panda_spherized.urdf of
https://github.com/KavrakiLab/vamp (Apache-2.0), which originates from
robowflex_resources (MIT). Kinematics use Franka's official modified DH
parameters; the URDF link frames of the Panda coincide with these DH frames,
which tests/fk_reference.rs checks. Spheres of the fixed links (link8, hand,
fingers) are re-expressed in the frame of joint 7.
"""

import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Franka Emika Panda, modified (Craig) DH parameters: a_{i-1}, d_i, alpha_{i-1}.
DH = [
    (0.0, 0.333, 0.0),
    (0.0, 0.0, -math.pi / 2),
    (0.0, 0.316, math.pi / 2),
    (0.0825, 0.0, math.pi / 2),
    (-0.0825, 0.384, -math.pi / 2),
    (0.0, 0.0, math.pi / 2),
    (0.088, 0.0, math.pi / 2),
]
# Official Franka Emika Panda joint limits (rad).
LIMITS = [
    (-2.8973, 2.8973),
    (-1.7628, 1.7628),
    (-2.8973, 2.8973),
    (-3.0718, -0.0698),
    (-2.8973, 2.8973),
    (-0.0175, 3.7525),
    (-2.8973, 2.8973),
]
# Fixed transforms of links rigidly attached to frame 7: (x, y, z, yaw).
FLANGE_Z = 0.107
HAND_YAW = -math.pi / 4
FINGER_Y = 0.065
FINGER_Z = 0.0584
TCP_Z = 0.1034


def rotz(yaw, p):
    c, s = math.cos(yaw), math.sin(yaw)
    return (c * p[0] - s * p[1], s * p[0] + c * p[1], p[2])


def to_frame7(link, p):
    if link == "panda_link8":
        return (p[0], p[1], p[2] + FLANGE_Z)
    if link == "panda_hand":
        x, y, z = rotz(HAND_YAW, p)
        return (x, y, z + FLANGE_Z)
    if link in ("panda_leftfinger", "panda_rightfinger"):
        sign = 1.0 if link == "panda_leftfinger" else -1.0
        hp = (p[0], p[1] + sign * FINGER_Y, p[2] + FINGER_Z)
        return to_frame7("panda_hand", hp)
    return p


FRAME = {f"panda_link{i}": i for i in range(8)}
FRAME.update({"panda_hand": 7, "panda_leftfinger": 7, "panda_rightfinger": 7})


def fmt(v):
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    return "0.0" if s in ("-0", "0") else (s if "." in s else s + ".0")


def main(resources):
    urdf = ET.parse(Path(resources) / "panda_spherized.urdf").getroot()
    srdf = ET.parse(Path(resources) / "panda.srdf").getroot()
    links = []
    for link in urdf.findall("link"):
        name = link.get("name")
        spheres = []
        for col in link.findall("collision"):
            sph = col.find("geometry/sphere")
            if sph is None:
                continue
            xyz = tuple(float(v) for v in col.find("origin").get("xyz").split())
            spheres.append((*to_frame7(name, xyz), float(sph.get("radius"))))
        if spheres:
            links.append((name, spheres))

    disabled = {
        frozenset((d.get("link1"), d.get("link2")))
        for d in srdf.findall("disable_collisions")
    }
    names = [n for n, _ in links]
    pairs = [
        (a, b)
        for i, a in enumerate(names)
        for b in names[i + 1:]
        if frozenset((a, b)) not in disabled
    ]

    out = []
    out.append("# Franka Emika Panda for motionAmigo. Generated by tools/gen_panda_toml.py.")
    out.append("# Kinematics: official Franka modified DH parameters and joint limits.")
    out.append("# Collision spheres: derived from VAMP resources/panda/panda_spherized.urdf")
    out.append("# (Apache-2.0, https://github.com/KavrakiLab/vamp), originally from")
    out.append("# robowflex_resources (MIT, https://github.com/KavrakiLab/robowflex_resources).")
    out.append("# Self-collision pairs: all sphere-carrying link pairs not disabled in panda.srdf.")
    out.append("")
    out.append('name = "panda"')
    out.append('convention = "modified_dh"')
    out.append("")
    out.append("self_collision = [")
    for a, b in pairs:
        out.append(f'  ["{a}", "{b}"],')
    out.append("]")
    out.append("")
    for i, ((a, d, alpha), (lo, hi)) in enumerate(zip(DH, LIMITS), start=1):
        out.append("[[joints]]")
        out.append(f'name = "panda_joint{i}"')
        out.append(f"a = {fmt(a)}")
        out.append(f"d = {fmt(d)}")
        out.append(f"alpha = {repr(alpha) if alpha else '0.0'}")
        out.append(f"lower = {fmt(lo)}")
        out.append(f"upper = {fmt(hi)}")
        out.append("")
    out.append("# Tool center point relative to the frame of the last joint:")
    out.append("# flange offset 0.107 m, hand rotated by -pi/4, TCP 0.1034 m below the hand.")
    out.append("[tcp]")
    out.append(f"xyz = [0.0, 0.0, {fmt(FLANGE_Z + TCP_Z)}]")
    out.append(f"rpy = [0.0, 0.0, {repr(HAND_YAW)}]")
    out.append("")
    for name, spheres in links:
        out.append("[[links]]")
        out.append(f'name = "{name}"')
        out.append(f"frame = {FRAME[name]}")
        out.append("spheres = [")
        for s in spheres:
            out.append("  [" + ", ".join(fmt(v) for v in s) + "],")
        out.append("]")
        out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
